### ISSUE TITLE
new repository template form repo type

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/.github#4]
If the repo type is selected as `private` we should ask what team should have access? Or maybe ask for some more information as to why it should be `private`?

![image](https://user-images.githubusercontent.com/8480023/191762995-868a5fe2-d263-4dd5-8c38-3bf57e0e1571.png)

**Comment by mwengren** [comment]
I don't believe we have any private repositories at the moment.  At one point before the Microsoft acquisition, I believe you could only create private repos with a paid subscription, which we did not have.  So all of our repos were public by necessity.  

By creating a public issue requesting a private repo, there's an element of privacy lost from the outset as well.  The only way to deal with that would be to just remove the private repo option leaving only 'public', and ask anyone needing a private repo to send us an email, which will clutter the form.

Or, we have a policy to only allow public repositories and revisit if needed in the future.  I'd still like to leave the dropdown with only one choice, since that gives a place to make the policy clear.  I added this dropdown choice only because it's there in GitHub's repo create form, and didn't really think it over. 

How does this approach sound?

**Comment by MathewBiddle** [comment]
Sounds good to me.

**Comment by mwengren** [comment]
Ok, this is done now.  I removed the new-repository.yml form from this repo so it's no longer organization-wide and it has been added to [ioos/governance](https://github.com/ioos/governance).  Made a few direct commits to speed things up.  

We can link directly [here](https://github.com/ioos/governance/issues/new?template=new-repository.yml) either from the README in this repo or link instead to ioos/goverance and describe the various options in the README there (once we have more than this single request type).
